spring:
  datasource:
    url: jdbc:mysql://patent-db-new.c05iwwo0ip8e.us-east-1.rds.amazonaws.com:3306/patent_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: tab20200782!

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계는 update, 운영 배포는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# ★ JWT 서명/검증에 사용할 고정 비밀키 (32바이트 이상)
security:
  jwt:
    secret: "change-this-to-your-256-bit-secret_______________________"
  jwt-validity-ms: 86400000   # 토큰 유효기간(ms)

# 외부 API 엔드포인트를 한 곳에서 관리
external-api:
  fastapi-ipc-url: "http://54.161.26.140:8000/predict"
  draft-url: "http://13.236.174.54:8000/analyze/"
  search-base-url: "http://43.201.66.246:8000"
  validation-url: "http://3.26.101.212:8000/api/ai/validations"
  claim-url: "https://neil-gordon-georgia-thumbnail.trycloudflare.com/generate"
  similar-search-base-url: "http://127.0.0.1:8000"
  three-d-model-endpoint: "https://4731cfc6a89a.ngrok-free.app/generate"

