spring:
  datasource:
    url: jdbc:mysql://patent-db-new.c05iwwo0ip8e.us-east-1.rds.amazonaws.com:3306/your_db_name?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: tab20200782!

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계는 update, 운영 배포는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# ★ JWT 서명/검증에 사용할 고정 비밀키 (32바이트 이상)
security:
  jwt:
    secret: "change-this-to-your-256-bit-secret_______________________"
  jwt-validity-ms: 86400000   # 토큰 유효기간(ms)

cors:
  allowed-origins:
    - http://35.175.253.22
    - http://35.175.253.22:3000
    - http://35.175.253.22:3001
    - http://35.175.253.22:3002
    - http://35.175.253.22:3003
    - http://35.175.253.22:5173
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:3003
