spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# ★ JWT 서명/검증에 사용할 고정 비밀키 (32바이트 이상)
security:
  jwt:
    secret: "change-this-to-your-256-bit-secret_______________________"
  # 선택: 유효기간(ms). JwtTokenProvider에서 @Value로 쓰거나 하드코딩해도 됨
  jwt-validity-ms: 86400000

cors:
  allowed-origins:
    - http://35.175.253.22
    - http://35.175.253.22:3000
    - http://35.175.253.22:3001
    - http://35.175.253.22:3002
    - http://35.175.253.22:3003
    - http://35.175.253.22:5173
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:3003
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD"
  allowed-headers: "*"

ai:
  search:
    base-url: http://43.201.66.246:8000
  similar-search:
    base-url: http://127.0.0.1:8000
  validation:
    url: http://3.26.101.212:8000/api/ai/validations
  claim-draft:
    url: https://neil-gordon-georgia-thumbnail.trycloudflare.com/generate
  draft:
    url: http://13.236.174.54:8000/analyze/
  ipc:
    url: http://54.161.26.140:8000/predict
  3d-model:
    endpoint: https://4731cfc6a89a.ngrok-free.app/generate
    save-dir: uploads
