spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# ★ JWT 서명/검증에 사용할 고정 비밀키 (32바이트 이상)
security:
  jwt:
    secret: "change-this-to-your-256-bit-secret_______________________"
  # 선택: 유효기간(ms). JwtTokenProvider에서 @Value로 쓰거나 하드코딩해도 됨
  jwt-validity-ms: 86400000

cors:
  allowed-origins:
    - http://35.175.253.22
    - http://35.175.253.22:3000
    - http://35.175.253.22:3001
    - http://35.175.253.22:3002
    - http://35.175.253.22:3003
    - http://35.175.253.22:5173
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:3003
