spring:
  h2:
    console:
      enabled: true
      path: /h2-console  # 기본 경로

  datasource:
    url: jdbc:h2:mem:testdb
#    jdbc:h2:file:./data/testdb 데이터를 계속 유지하려면 변경
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
