spring:
  datasource:
    url: jdbc:mysql://patent-db-new.c05iwow0ip8e.us-east-1.rds.amazonaws.com:3306/patent_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: tab20200782!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# ★ JWT 서명/검증에 사용할 고정 비밀키 (32바이트 이상)
security:
  jwt:
    secret: "change-this-to-your-256-bit-secret_______________________"
  # 선택: 유효기간(ms). JwtTokenProvider에서 @Value로 쓰거나 하드코딩해도 됨
  jwt-validity-ms: 86400000
