name: CD backend → EC2 (CICD)

on:
  push:
    branches: [ "CICD" ]        # ★ CICD 브랜치에 푸시될 때만
    paths:
      - "backend/**"            # backend 변경에만 트리거 (원하면 삭제 가능)
  workflow_dispatch:             # 수동 실행 버튼

concurrency:
  group: cd-ec2-backend
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EC2_APP_DIR: /home/${{ secrets.USERNAME }}/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make gradlew executable
        working-directory: backend
        run: chmod +x gradlew

      - name: Build (Gradle bootJar)
        working-directory: backend
        run: ./gradlew clean bootJar -x test

      - name: Find artifact (jar path)
        id: findjar
        shell: bash
        run: |
          JAR=$(ls -t backend/build/libs/*.jar | head -n 1)
          echo "jar=$JAR" >> $GITHUB_OUTPUT
          echo "Found JAR: $JAR"

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ${{ steps.findjar.outputs.jar }}
          target: ${{ env.EC2_APP_DIR }}/releases/
          strip_components: 0
          overwrite: true

      - name: Restart service on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            APP_DIR="/home/ubuntu/app"   # EC2에서 앱이 설치된 절대경로
            LATEST_JAR=$(ls -t "$APP_DIR"/releases/*.jar | head -n 1)
            echo "Latest jar: $LATEST_JAR"
            "$APP_DIR"/deploy.sh "$LATEST_JAR"
            sleep 2
            curl -fsS "http://127.0.0.1:${APP_PORT:-8080}/actuator/health" || curl -fsS "http://127.0.0.1:${APP_PORT:-8080}" || true
