name: CD frontends → EC2

on:
  push:
    branches: ["CICD"]           # 배포 브랜치
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fe: [applicant_fe, examiner_fe]

    defaults:
      run:
        working-directory: frontend/${{ matrix.fe }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/${{ matrix.fe }}/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # (선행) 원격에 목적지 폴더 보장
      - name: Ensure remote dirs
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            mkdir -p /home/${{ secrets.USERNAME }}/fe/applicant_fe
            mkdir -p /home/${{ secrets.USERNAME }}/fe/examiner_fe

      # dist 업로드 (정적 파일만)
      - name: Upload dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # dist/** 로 해야 하위폴더(assets 등) 포함
          source: frontend/${{ matrix.fe }}/dist/**
          target: /home/${{ secrets.USERNAME }}/fe/${{ matrix.fe }}/
          strip_components: 3
          overwrite: true

      # 권한/접근 + Nginx reload + 헬스체크
      - name: Fix perms & reload Nginx
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            APP_NAME="${{ matrix.fe }}"
            APP_DIR="/home/${{ secrets.USERNAME }}/fe/${APP_NAME}"

            # 상위경로 traversal 권한(o+x) & 파일 읽기(o+r)
            chmod o+x /home/${{ secrets.USERNAME }} || true
            chmod o+x /home/${{ secrets.USERNAME }}/fe || true
            chmod -R o+r "$APP_DIR" || true

            # Nginx 설정 검사 후 무중단 reload
            sudo nginx -t
            sudo systemctl reload nginx

            # 간단 헬스체크 (로컬에서 80으로 확인)
            URL_PATH=$([ "$APP_NAME" = "applicant_fe" ] && echo "/applicant/" || echo "/examiner/")
            curl -Is "http://127.0.0.1${URL_PATH}" | head -n1 || true

