name: CD frontends → EC2
on:
  push:
    branches: ["CICD"]        # 원하는 배포 브랜치
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fe: [applicant_fe, examiner_fe]
    defaults:
      run:
        working-directory: frontend/${{ matrix.fe }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/${{ matrix.fe }}/package-lock.json

      - run: npm ci
      - run: npm run build            # dev 대신 build 후 dist 사용

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "frontend/${{ matrix.fe }}/dist/*"
          target: "/home/${{ secrets.USERNAME }}/fe/${{ matrix.fe }}/"
          strip_components: 3
          overwrite: true

      - name: Restart pm2 (no tail)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            # nvm / npm-global 경로 로드 (pm2 못 찾는 문제 예방)
            if [ -s "$HOME/.nvm/nvm.sh" ]; then . "$HOME/.nvm/nvm.sh"; nvm use 18 >/dev/null 2>&1 || true; fi
            export PATH="$HOME/.npm-global/bin:$PATH"
      
            APP_NAME="${{ matrix.fe }}"
            APP_DIR="/home/${{ secrets.USERNAME }}/fe/${APP_NAME}"
            PORT=$([ "$APP_NAME" = "applicant_fe" ] && echo 3000 || echo 3001)
      
            # pm2 재시작(없으면 최초 serve) + 저장
            # [수정] serve 실행 시 -f 옵션을 추가하여 이미 실행 중인 스크립트를 강제로 덮어씌웁니다.
            pm2 reload "$APP_NAME" || pm2 serve "$APP_DIR" "$PORT" --spa --name "$APP_NAME" -f
            pm2 save
      
            # 상태 한 줄 + 간단 헬스체크 (tail 금지)
            pm2 list | grep "$APP_NAME" || true
            curl -Is "http://127.0.0.1:${PORT}" | head -n1 || true
